name: CI

on:
  pull_request:
    branches:
      - main

env:
  JAVA_VERSION: 21
  JAVA_DISTRIBUTION: 'adopt'

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Code
        uses: actions/checkout@v3

      - name: Set up JDK $JAVA_VERSION
        uses: actions/setup-java@v3
        with:
          java-version: $JAVA_VERSION
          distribution: $JAVA_DISTRIBUTION

      - name: Build with Maven
        run: mvn clean install